# SPDX-License-Identifier: MIT
# Copyright (c) Enchanter Labs
"""golem._ffi — loader for the gopy-generated CPython extension.

This module is the single place that imports the compiled Go core. Everything
Pythonic lives in ``golem/__init__.py``; this file only locates and exposes the
gopy-generated handle module so the rest of the package never touches build
details.

==============================================================================
How the extension is generated (gopy)
==============================================================================
golem's Python binding is generated by gopy (github.com/go-python/gopy) — it is
NOT a hand-rolled C ABI. gopy emits a CPython extension plus GC-safe,
handle-based marshalling, so the Go ``*Engine`` and ``*Program`` structs cross
the boundary as opaque handles rather than being re-implemented in Python.

The exact, reproducible invocation (also wired into the repo's Makefile
``gopy`` target and ``.github/workflows/wheels.yml`` so the wheel build is
hermetic) is:

    # Pinned tools (reproducible; versions also pinned in wheels.yml):
    #   go install github.com/go-python/gopy@v0.4.10
    #   go install golang.org/x/tools/cmd/goimports@latest
    #   python -m pip install pybindgen
    #
    # From the repo root, generate the extension package named "_golem" into
    # python/golem/ so it sits next to this loader:
    #
    #   gopy build -output=python/golem/_golem \
    #       -name=_golem \
    #       -vm=python3 \
    #       github.com/enchanter-ai/golem
    #
    # gopy build produces:
    #   python/golem/_golem/__init__.py   (the Python-facing handle module)
    #   python/golem/_golem/_golem*.so    (the compiled CPython extension)
    #   plus generated .c/.go/.h glue.
    #
    # These generated files are NOT committed to the repo (see .gitignore and
    # the <binding> contract). cibuildwheel runs `gopy build` inside each wheel
    # job so `pip install enchanter-golem` needs no Go/C toolchain on the user's machine.

==============================================================================
Why a JSON envelope crosses the boundary (gopy issue #254)
==============================================================================
The dynamic evaluation path (variables in, value out) does NOT return a Go
``(value, error)`` pair across the gopy boundary. gopy's ``(value, error)`` ->
Python-exception mapping is BUGGY for ``(string, error)`` — go-python/gopy
issue #254, "returned a result with an error set" — so a Go error raised across
the boundary corrupts the call. golem therefore routes every dynamic outcome,
success or failure, through ``Engine.EvalJSON(src, varsJSON) string``, which
returns a SINGLE self-describing JSON ENVELOPE and never a Go error:

    success: {"ok": true,  "type": "int|float|bool|string|null", "value": <json>}
    failure: {"ok": false, "errtype": "<TypedErrorName>", "error": "<message>"}

``golem/__init__.py`` parses that envelope, restores the Python type from the
"type" tag (so a float ``2.0`` stays a Python float even though JSON renders it
``2``), and raises the mapped exception when ``ok`` is false. The same envelope
discipline is mirrored for Engine construction (see ``NewEngineJSON`` below),
because the configuration carries a ``map[string]any`` variable schema that gopy
also marshals poorly.
"""

from __future__ import annotations

import importlib
from types import ModuleType
from typing import Optional

# Name of the gopy-generated extension package (see the invocation above).
_EXTENSION_MODULE = "golem._golem"

_ext: Optional[ModuleType] = None


class ExtensionNotBuilt(ImportError):
    """Raised when the gopy-generated extension has not been built/installed.

    Installing a prebuilt wheel (``pip install enchanter-golem``) bundles the compiled
    extension. Building from source requires running the ``gopy build``
    invocation documented at the top of this module first.
    """


def load_extension() -> ModuleType:
    """Import and cache the gopy-generated extension module.

    The compiled module exposes the Go core's bound surface. golem only relies
    on three pieces of it, all of which gopy can bind cleanly:

      * ``New() *Engine``                      -> zero-config engine handle.
      * ``NewEngineJSON(optionsJSON) *Engine`` -> configured engine handle; the
        engine configuration (variable schema, strict flag, cache size, cost
        limit, timeout) crosses as a JSON string for exactly the same reason
        EvalJSON does — gopy marshals ``map[string]any`` and variadic
        functional options poorly. This constructor is the symmetric companion
        of ``EvalJSON`` on the Go side.
      * the bound ``Engine`` handle's ``EvalJSON(src, varsJSON) str`` method.

    NOTE (capability gap, surfaced not hidden): ``NewEngineJSON`` is a Go-core
    (N1) boundary. If a given build of the core predates it, ``Engine`` with
    configuration cannot be constructed via gopy and ``golem/__init__.py``
    falls back to the bare ``New()`` handle for the zero-config case only,
    raising a clear error for the configured case rather than silently
    dropping the schema. golem never silently degrades a declared schema into
    a lenient engine — that would defeat the LOUD contract.
    """
    global _ext
    if _ext is not None:
        return _ext
    try:
        _ext = importlib.import_module(_EXTENSION_MODULE)
    except ImportError as exc:  # pragma: no cover - exercised only without a build
        raise ExtensionNotBuilt(
            "the gopy-generated golem extension is not built. Install a prebuilt "
            "wheel with `pip install enchanter-golem`, or build from source by running the "
            "`gopy build` invocation documented in golem/_ffi.py."
        ) from exc
    return _ext
